version: "3"
services:
 api:
    env_file:
     - ./.env
    build: 
      context: .docker
      args:
        - JAVA_HOME_DOCKER=${JAVA_HOME_DOCKER}
        - MAVEN=${MAVEN}
    container_name: ${CONTAINER_NAME_API}
    restart: always
    volumes:
     - ./:/App:rw
 db:
    image: mysql:5.7
    env_file:
     - ./.env
    restart: always
    container_name: ${CONTAINER_NAME_DB}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql:rw
networks:
  default:
    external:
      name: ${NETWORK_CONTAINER}

