---
# Staging Profile 
server:
  port: 8090
spring:
  profiles: stage
  datasource:
    driverClassName: 
    password: 
    url: 
    username: 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 
        format_sql: true
    show-sql: true
  security:
    user:
      name: 
      password: 
  flyway:
    user: 
    password: 
    schemas:
    url:
    locations: