---
# Production Profile 
server:
  port: 8090
spring:
  profiles: prod
  datasource:
    driverClassName: 
    password: 
    url: 
    username: 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: 
        format_sql: true
    show-sql: true