---
# Staging Profile 
server:
  port: 8092
spring:
  profiles: production
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: ysae
    url: jdbc:sqlserver://BRSPOSQLHML:1433;database=EDE71_ODPV_PREPRD
    username: easy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true